.\" $NetBSD: $
.\"
.\" Copyright (c) 2014, 2015 David Carlier <devnexen@gmail.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF MIND, USE, DATA OR PROFITS, WHETHER IN
.\" AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT
.\" OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: November 03 2015 $
.Dt GEOLOCD.CONF 5
.Os
.Sh NAME
.Nm geolocd.conf
.Nd GeoLocalisation daemon configuration file
.Sh DESCRIPTION
This manual page describes the format of the
.Xr geolocd 8
configuration file.
.Sh SECTIONS
.Nm
Two directives
.Bl -tag -width xxxx
.It backend
backend name (geoip)
.It datafile
database's file absolute file path
.Sh FILES
.Bl -tag -width "/etc/geolocd.conf"
.It Pa /etc/geolocd.conf
.Xr geolocd.8
configuration file
.Sh SEE ALSO
.Xr geolocd.8
.El
.Sh HISTORY
The
.Nm
file format first appeared in
.Nx 7.99 .
